# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test0327.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(768, 670)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 185, 670))
        self.groupBox.setMouseTracking(True)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.la_totaldef = QtWidgets.QLabel(self.groupBox)
        self.la_totaldef.setGeometry(QtCore.QRect(96, 530, 121, 21))
        self.la_totaldef.setObjectName("la_totaldef")
        self.la_totaldeth = QtWidgets.QLabel(self.groupBox)
        self.la_totaldeth.setGeometry(QtCore.QRect(96, 610, 61, 21))
        self.la_totaldeth.setObjectName("la_totaldeth")
        self.la_totaltre = QtWidgets.QLabel(self.groupBox)
        self.la_totaltre.setGeometry(QtCore.QRect(96, 570, 121, 21))
        self.la_totaltre.setObjectName("la_totaltre")
        self.la_dailydeth = QtWidgets.QLabel(self.groupBox)
        self.la_dailydeth.setGeometry(QtCore.QRect(96, 429, 81, 21))
        self.la_dailydeth.setObjectName("la_dailydeth")
        self.la_dailydef = QtWidgets.QLabel(self.groupBox)
        self.la_dailydef.setGeometry(QtCore.QRect(96, 350, 81, 21))
        self.la_dailydef.setObjectName("la_dailydef")
        self.la_dailytre = QtWidgets.QLabel(self.groupBox)
        self.la_dailytre.setGeometry(QtCore.QRect(96, 390, 81, 21))
        self.la_dailytre.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.la_dailytre.setMouseTracking(True)
        self.la_dailytre.setTabletTracking(False)
        self.la_dailytre.setObjectName("la_dailytre")
        self.la_date = QtWidgets.QLabel(self.groupBox)
        self.la_date.setGeometry(QtCore.QRect(20, 200, 150, 81))
        self.la_date.setStyleSheet("font: 28pt \"맑은 고딕\";")
        self.la_date.setObjectName("la_date")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(55, 41, 91, 131))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cb_definite = QtWidgets.QCheckBox(self.widget)
        self.cb_definite.setStyleSheet("font: 75 13pt \"Adobe Arabic\";")
        self.cb_definite.setObjectName("cb_definite")
        self.verticalLayout.addWidget(self.cb_definite)
        self.cb_death = QtWidgets.QCheckBox(self.widget)
        self.cb_death.setStyleSheet("font: 75 13pt \"Adobe Arabic\";")
        self.cb_death.setObjectName("cb_death")
        self.verticalLayout.addWidget(self.cb_death)
        self.cb_treate = QtWidgets.QCheckBox(self.widget)
        self.cb_treate.setStyleSheet("font: 75 13pt \"Adobe Arabic\";")
        self.cb_treate.setObjectName("cb_treate")
        self.verticalLayout.addWidget(self.cb_treate)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(0, -10, 781, 681))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("img_source/chart_layout.jpg"))
        self.label_7.setObjectName("label_7")
        self.label_7.raise_()
        self.ScrollbarDate = QtWidgets.QScrollBar(Form)
        self.ScrollbarDate.setGeometry(QtCore.QRect(200, 646, 561, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ScrollbarDate.sizePolicy().hasHeightForWidth())
        self.ScrollbarDate.setSizePolicy(sizePolicy)
        self.ScrollbarDate.setOrientation(QtCore.Qt.Horizontal)
        self.ScrollbarDate.setObjectName("ScrollbarDate")
        self.ScrollbarDate.raise_()
        self.groupBox.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.la_totaldef.setText(_translate("Form", "누적확진자"))
        self.la_totaldeth.setText(_translate("Form", "누적사망자"))
        self.la_totaltre.setText(_translate("Form", "누적완치자"))
        self.la_dailydeth.setText(_translate("Form", "사망자"))
        self.la_dailydef.setText(_translate("Form", "확진자"))
        self.la_dailytre.setText(_translate("Form", "완치자"))
        self.la_date.setText(_translate("Form", ""))
        self.cb_definite.setText(_translate("Form", "확진자"))
        self.cb_death.setText(_translate("Form", "사망자"))
        self.cb_treate.setText(_translate("Form", "완치자"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
